apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-zsrq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-zsrq
    app.kubernetes.io/part-of: jvm-build-suite-application-biyb
  name: jvm-build-suite-component-zsrq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-zsrq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-zsrq
    spec:
      containers:
      - image: quay.io/qijing/jvm-build-mdmy-tenant/jvm-build-suite-application-biyb/jvm-build-suite-component-zsrq@sha256:4063f49f45b1b60949abb802da4f5ecac65ece333a81669444493ce3e0f0a34d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
