apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-zsrq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/jvm-build-mdmy-tenant/jvm-build-suite-application-biyb/jvm-build-suite-component-zsrq@sha256:cc44ce547ef71e6b5cae6d768c61d12f46f88f4d763c5c2d946e403e86645d24
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
